In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas import DataFrame, Series, read_csv
%matplotlib inline

In [3]:
pwd

'C:\\Users\\aaron\\documents\\py36\\software\\scattersim-examples'

In [6]:
path = "D:\\data\\Tracking\\7_7_2017\\AG_solid\\all tracks\\1 2017-06-16 11-40-27_AllTracks.csv"
df = read_csv(path)

In [7]:
df.head()

,Particle ID,Size/nm,Diffusion coefficient/nm^2 s^-1,Frame,X/pixels,Y/pixels,Ln(Adjusted intensity)/AU,Included in distribution?,Unnamed: 8
0,0,94.4954,5085830.0,0,524.677,7.96822,10.6029,False,NaN
1,0,94.4954,5085830.0,1,521.529,7.35267,10.3895,False,NaN
2,0,94.4954,5085830.0,2,526.905,7.15157,10.4838,False,NaN
3,1,38.5461,12467900.0,0,400.126,15.60100,10.5336,False,NaN
4,1,38.5461,12467900.0,1,399.224,8.69669,10.6623,False,NaN

In [8]:
df['Size/nm'].mean()
df['Diffusion coefficient/nm^2 s^-1'].mean()

8571315.493067097

In [11]:
import os

topdir = 'D:\\data\\Tracking\\7_7_2017\\AG_solid\\all tracks\\'
ext ='.csv'

P = DataFrame()
for dirpath, dirnames, files in os.walk(topdir):
    print(files)
    
for file in files:
    path1 =topdir+file
    df = read_csv(path1)
    Name = '%s' % file
    
    size = df['Size/nm']
    diffusion = df['Diffusion coefficient/nm^2 s^-1']
    
    P=P.assign(Size=size)
    P=P.assign(Diffusion=diffusion)

['1 2017-06-16 11-40-27_AllTracks.csv', '3 2017-07-07 10-10-35_AllTracks.csv', '3 2017-07-07 10-13-24_AllTracks.csv', '3 2017-07-07 10-17-29_AllTracks.csv', '3 2017-07-07 10-24-38_AllTracks.csv', '3 2017-07-07 10-29-06_AllTracks.csv', '3 2017-07-07 10-30-18_AllTracks.csv', '3 2017-07-07 10-32-16_AllTracks.csv', '3 2017-07-07 10-34-07_AllTracks.csv', '3 2017-07-07 10-38-41_AllTracks.csv', '3 2017-07-07 10-52-08_AllTracks.csv', '3 2017-07-07 10-55-53_AllTracks.csv', '3 2017-07-07 11-01-04_AllTracks.csv']

In [12]:
P

           Size  Diffusion
0       182.035  2607260.0
1       182.035  2607260.0
2       182.035  2607260.0
3       172.254  2755320.0
4       172.254  2755320.0
5       151.626  3130160.0
6       151.626  3130160.0
7       221.583  2141920.0
8       221.583  2141920.0
9       221.583  2141920.0
10      221.583  2141920.0
11      221.583  2141920.0
12      221.583  2141920.0
13      221.583  2141920.0
14      221.583  2141920.0
15      221.583  2141920.0
16      221.583  2141920.0
17      221.583  2141920.0
18      221.583  2141920.0
19      221.583  2141920.0
20      221.583  2141920.0
21      221.583  2141920.0
22      221.583  2141920.0
23      221.583  2141920.0
24      221.583  2141920.0
25      221.583  2141920.0
26      221.583  2141920.0
27      221.583  2141920.0
28      221.583  2141920.0
29      221.583  2141920.0
...         ...        ...
267378      NaN        NaN
267379      NaN        NaN
267380      NaN        NaN
267381      NaN        NaN
267382      NaN        NaN
267383      NaN        NaN
267384      NaN        NaN
267385      NaN        NaN
267386      NaN        NaN
267387      NaN        NaN
267388      NaN        NaN
267389      NaN        NaN
267390      NaN        NaN
267391      NaN        NaN
267392      NaN        NaN
267393      NaN        NaN
267394      NaN        NaN
267395      NaN        NaN
267396      NaN        NaN
267397      NaN        NaN
267398      NaN        NaN
267399      NaN        NaN
267400      NaN        NaN
267401      NaN        NaN
267402      NaN        NaN
267403      NaN        NaN
267404      NaN        NaN
267405      NaN        NaN
267406      NaN        NaN
267407      NaN        NaN

[267408 rows x 2 columns]

In [48]:
diffusion = df['Diffusion coefficient/nm^2 s^-1']

In [54]:
T = DataFrame()

files = ['1 2017-06-16 11-40-27_AllTracks.csv', 'test']

T['size'+'1']=df['Size/nm']

T =T.assign(Diffusion=diffusion)
T

          size1  Diffusion
0      182.0350  2607260.0
1      182.0350  2607260.0
2      182.0350  2607260.0
3      172.2540  2755320.0
4      172.2540  2755320.0
5      151.6260  3130160.0
6      151.6260  3130160.0
7      221.5830  2141920.0
8      221.5830  2141920.0
9      221.5830  2141920.0
10     221.5830  2141920.0
11     221.5830  2141920.0
12     221.5830  2141920.0
13     221.5830  2141920.0
14     221.5830  2141920.0
15     221.5830  2141920.0
16     221.5830  2141920.0
17     221.5830  2141920.0
18     221.5830  2141920.0
19     221.5830  2141920.0
20     221.5830  2141920.0
21     221.5830  2141920.0
22     221.5830  2141920.0
23     221.5830  2141920.0
24     221.5830  2141920.0
25     221.5830  2141920.0
26     221.5830  2141920.0
27     221.5830  2141920.0
28     221.5830  2141920.0
29     221.5830  2141920.0
...         ...        ...
9722   239.0680  1985270.0
9723   239.0680  1985270.0
9724   239.0680  1985270.0
9725   239.0680  1985270.0
9726   239.0680  1985270.0
9727   239.0680  1985270.0
9728   239.0680  1985270.0
9729   239.0680  1985270.0
9730   239.0680  1985270.0
9731    83.3855  5691800.0
9732    83.3855  5691800.0
9733   109.1610  4347820.0
9734   109.1610  4347820.0
9735   109.1610  4347820.0
9736   109.1610  4347820.0
9737   109.1610  4347820.0
9738   636.8550   745247.0
9739   636.8550   745247.0
9740    48.7531  9735060.0
9741    48.7531  9735060.0
9742    48.7531  9735060.0
9743  6883.8400    68946.1
9744  6883.8400    68946.1
9745   440.1310  1078350.0
9746   440.1310  1078350.0
9747   129.5300  3664130.0
9748   129.5300  3664130.0
9749   129.5300  3664130.0
9750   129.5300  3664130.0
9751   129.5300  3664130.0

[9752 rows x 2 columns]

In [ ]:
#assign
#nested dictionary
#http://pandas.pydata.org/pandas-docs/stable/10min.html
#https://stackoverflow.com/questions/31247198/python-pandas-write-content-of-dataframe-into-text-file
#http://pythoncentral.io/recursive-file-and-directory-manipulation-in-python-part-1/
#https://www.daniweb.com/programming/software-development/threads/497685/using-pandas-to-merge-concatenate-multiple-csv-files-into-one-csv-file
#http://docs.enthought.com/mayavi/mayavi/overview.html